global:
  scrape_interval: 15s # Default scrape interval
  evaluation_interval: 15s
  external_labels:
    monitor: 'ritchy-monitor'

scrape_configs:
  - job_name: 'ritchy-api'
    static_configs:
      - targets: ['api.railway.internal']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # - job_name: 'example_api'
  #   scheme: http
  #   static_configs:
  #     - targets: ['example_api:9091']

  #  ? TODO: add your services here
  # - job_name: 'your-job-name'
  #   scheme: https
  #   static_configs:
  #     - targets: ['URL_GOES_HERE']
  #   basic_auth:
  #     username: HTTP_AUTH_USERNAME_GOES_HERE
  #     password: HTTP_AUTH_PASSWORD_GOES_HERE